from __future__ import annotations

from fastapi import APIRouter, Depends

from app.api.v1 import (
    finance_ops,
    finance_control_tower,
    finance_writable,
    hr_ops,
    admin,
    admin_support,
    assignment_acceptance,
    assignments,
    billing_approvals,
    therapist_transitions,
    attachments,
    auth,
    notifications,
    cases,
    meetings,
    daily_logs,
    hr,
    incidents,
    invoices,
    leave,
    parent,
    reports,
    sessions,
    booking,
    slots,
    scheduling,
    tickets,
    support,
    therapist_profile,
    therapist_portal,
    geocode,
    files,
    client_billing,
    ledger_billing,
    case_documents,
    case_services,
    session_absence,
    memos,
    clinical_reports,
)
from app.core.feature_flags import require_billing, require_clinical_reports_engine

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(notifications.router)
api_router.include_router(meetings.router)
api_router.include_router(meetings.compat_router)
api_router.include_router(cases.router)
api_router.include_router(billing_approvals.router)
api_router.include_router(case_services.router)
api_router.include_router(assignments.router)
api_router.include_router(therapist_transitions.router)
api_router.include_router(assignment_acceptance.router)
api_router.include_router(sessions.router)
api_router.include_router(session_absence.router)
api_router.include_router(daily_logs.router)
api_router.include_router(reports.router)
api_router.include_router(invoices.router)
api_router.include_router(admin.router)
api_router.include_router(
    finance_ops.router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(
    finance_control_tower.router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(
    finance_writable.router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(hr_ops.router)
api_router.include_router(admin_support.router)
api_router.include_router(parent.router)
api_router.include_router(
    client_billing.parent_router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(
    client_billing.admin_router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(
    ledger_billing.router,
    dependencies=[Depends(require_billing)],
)
api_router.include_router(tickets.router)
api_router.include_router(support.router)
api_router.include_router(attachments.router)
api_router.include_router(incidents.router)
api_router.include_router(leave.router)
api_router.include_router(slots.router)
api_router.include_router(scheduling.router)
api_router.include_router(booking.router)
api_router.include_router(hr.router)
api_router.include_router(therapist_profile.router)
api_router.include_router(therapist_portal.router)
api_router.include_router(geocode.router)
api_router.include_router(files.router)
api_router.include_router(case_documents.router)
api_router.include_router(case_documents.documents_router)
api_router.include_router(memos.router)
api_router.include_router(
    clinical_reports.router,
    dependencies=[Depends(require_clinical_reports_engine)],
)
