import { useState } from 'react'
import { apiDownload, apiFetch } from '../../lib/apiClient.js'
import { AdminPanel } from './ui/index.js'
import { BillingActionAlert } from './ui/BillingActionAlert.jsx'
import { useBillingAction } from '../../hooks/useBillingAction.js'
import './admin-hr-reports.css'

const REPORT_KEY = 'therapist-payout-preview'
const REPORT_LABEL = 'Therapist payout preview'

export function AdminFinanceReportsTab() {
  const [billingMonth, setBillingMonth] = useState(() => new Date().toISOString().slice(0, 7))
  const [preview, setPreview] = useState(null)
  const [monthClose, setMonthClose] = useState(null)
  const { loading, error, successMessage, run, clearMessages } = useBillingAction()

  async function loadMonthCloseStatus(ym) {
    try {
      const data = await apiFetch(
        `/api/v1/admin/finance-reports/billing-month-close?billing_month=${encodeURIComponent(ym)}`,
      )
      setMonthClose(data)
    } catch {
      setMonthClose(null)
    }
  }

  async function loadPreview() {
    const data = await run(
      () =>
        apiFetch(
          `/api/v1/admin/finance-reports/${REPORT_KEY}?billing_month=${encodeURIComponent(billingMonth)}`,
        ),
      { successMsg: 'Report loaded' },
    )
    setPreview(data)
    await loadMonthCloseStatus(billingMonth)
  }

  async function closeBillingMonth() {
    await run(
      () =>
        apiFetch('/api/v1/admin/finance-reports/close-billing-month', {
          method: 'POST',
          body: JSON.stringify({ billing_month: billingMonth }),
        }),
      { successMsg: `Billing month ${billingMonth} closed and snapshotted` },
    )
    await loadMonthCloseStatus(billingMonth)
    await loadPreview()
  }

  async function downloadCsv() {
    await run(
      () =>
        apiDownload(
          `/api/v1/admin/finance-reports/${REPORT_KEY}?billing_month=${encodeURIComponent(billingMonth)}&format=csv`,
          `${REPORT_KEY}.csv`,
        ),
      { successMsg: 'CSV downloaded' },
    )
  }

  async function downloadExcel() {
    await run(
      () =>
        apiDownload(
          `/api/v1/admin/finance-reports/${REPORT_KEY}?billing_month=${encodeURIComponent(billingMonth)}&format=xlsx`,
          `${REPORT_KEY}.xlsx`,
        ),
      { successMsg: 'Excel downloaded' },
    )
  }

  return (
    <div className="admin-hr-reports">
      <AdminPanel title={REPORT_LABEL} padded>
        <BillingActionAlert error={error} successMessage={successMessage} onDismiss={clearMessages} />
        <p className="admin-muted admin-hr-reports__hint">
          Projected therapist payout before month close. Set the billing month, then preview or download. Close month
          freezes payout preview snapshots.
        </p>
        <div className="admin-hr-reports__filters">
          <label className="client-inv__filter-field">
            <span className="client-inv__filter-label">Billing month</span>
            <input
              type="month"
              className="client-inv__filter-input"
              value={billingMonth}
              onChange={(e) => setBillingMonth(e.target.value)}
            />
          </label>
        </div>
        <div className="admin-hr-reports__actions admin-btn-group">
          <button
            type="button"
            className="admin-btn admin-btn--primary admin-btn--sm"
            disabled={loading}
            onClick={loadPreview}
          >
            {loading ? 'Loading…' : 'Preview'}
          </button>
          <button
            type="button"
            className="admin-btn admin-btn--secondary admin-btn--sm"
            disabled={loading}
            onClick={downloadCsv}
          >
            CSV
          </button>
          <button
            type="button"
            className="admin-btn admin-btn--secondary admin-btn--sm"
            disabled={loading}
            onClick={downloadExcel}
          >
            Excel
          </button>
          <button
            type="button"
            className="admin-btn admin-btn--ghost admin-btn--sm"
            disabled={loading || monthClose?.closed}
            onClick={closeBillingMonth}
            title="Freeze payout preview data for this billing month"
          >
            {monthClose?.closed ? 'Month closed' : 'Close month'}
          </button>
        </div>

        {monthClose?.closed ? (
          <p className="admin-muted" style={{ marginTop: 12 }}>
            {billingMonth} is closed — payout preview reads frozen snapshots.
            {monthClose.closedAt ? ` Closed ${new Date(monthClose.closedAt).toLocaleString()}.` : ''}
          </p>
        ) : null}
        {preview?.dataSource === 'snapshot' ? (
          <p className="admin-muted" style={{ marginTop: 8 }}>
            Data source: frozen snapshot (not live case rates).
          </p>
        ) : null}
        {preview?.generatedAt ? (
          <p className="admin-muted" style={{ marginTop: 8 }}>
            Generated by <strong>{preview.generatedBy}</strong> on {preview.generatedAt}
          </p>
        ) : null}

        {preview?.rows?.length ? (
          <div className="admin-table-wrap" style={{ marginTop: 16 }}>
            <table className="admin-table">
              <thead>
                <tr>
                  {Object.keys(preview.rows[0]).map((k) => (
                    <th key={k}>{k}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {preview.rows.slice(0, 50).map((row, i) => (
                  <tr key={i}>
                    {Object.values(row).map((v, j) => (
                      <td key={j}>{typeof v === 'boolean' ? (v ? 'true' : 'false') : String(v ?? '')}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
            {preview.rows.length > 50 ? (
              <p className="admin-muted">Showing first 50 of {preview.count} rows.</p>
            ) : null}
          </div>
        ) : preview ? (
          <p className="admin-muted" style={{ marginTop: 12 }}>
            No rows for this billing month. Try another month, or confirm billing data exists for these cases.
          </p>
        ) : null}
      </AdminPanel>
    </div>
  )
}
