from __future__ import annotations

from datetime import datetime, timezone

from app.models.user import User


def export_actor_label(user: User) -> str:
    return (user.full_name or user.email or f"User #{user.id}").strip()


def export_timestamp_label(now: datetime | None = None) -> str:
    ts = now or datetime.now(timezone.utc)
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    return ts.strftime("%Y-%m-%d %H:%M UTC")


def export_meta(user: User) -> dict[str, str]:
    return {
        "generated_by": export_actor_label(user),
        "generated_at": export_timestamp_label(),
    }


def xlsx_preamble_rows(title: str, subtitle: str | None, meta: dict[str, str]) -> list[list]:
    rows: list[list] = [[title]]
    if subtitle:
        rows.append([subtitle])
    rows.append([f"Generated by: {meta['generated_by']} · {meta['generated_at']}"])
    rows.append([])
    return rows


def xlsx_footer_rows(meta: dict[str, str]) -> list[list]:
    return [[], [f"Document generated by {meta['generated_by']} on {meta['generated_at']}"]]
