"""CSV, Excel, and PDF export for operational reports."""
from __future__ import annotations

import csv
import io
from typing import Any

from app.models.user import User
from app.services.export_document_service import export_meta, xlsx_footer_rows, xlsx_preamble_rows


def rows_to_csv(rows: list[dict[str, Any]]) -> str:
    if not rows:
        buf = io.StringIO()
        writer = csv.writer(buf)
        writer.writerow(["message"])
        writer.writerow(["No rows for the selected filters"])
        return buf.getvalue()
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    for row in rows:
        writer.writerow({k: row.get(k, "") for k in rows[0].keys()})
    return buf.getvalue()


def payload_to_xlsx(
    *,
    title: str,
    subtitle: str,
    user: User,
    rows: list[dict[str, Any]],
    sheets: dict[str, list[dict[str, Any]]] | None = None,
) -> bytes:
    import openpyxl

    meta = export_meta(user)
    wb = openpyxl.Workbook()
    sheet_map = sheets or {"Report": rows}

    first = True
    for sheet_name, sheet_rows in sheet_map.items():
        if first:
            ws = wb.active
            ws.title = sheet_name[:31]
            first = False
        else:
            ws = wb.create_sheet(title=sheet_name[:31])
        for row in xlsx_preamble_rows(title, subtitle, meta):
            ws.append(row)
        if sheet_rows:
            headers = list(sheet_rows[0].keys())
            ws.append(headers)
            for item in sheet_rows:
                ws.append([item.get(h, "") for h in headers])
        else:
            ws.append(["message", "No rows for the selected filters"])
        for row in xlsx_footer_rows(meta):
            ws.append(row)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def payload_to_pdf(
    *,
    title: str,
    subtitle: str,
    user: User,
    rows: list[dict[str, Any]],
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import landscape, letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    meta = export_meta(user)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(letter))
    styles = getSampleStyleSheet()
    story = [
        Paragraph(title, styles["Title"]),
        Paragraph(subtitle, styles["Normal"]),
        Paragraph(f"Generated by {meta['generated_by']} · {meta['generated_at']}", styles["Normal"]),
        Spacer(1, 12),
    ]

    if not rows:
        story.append(Paragraph("No rows for the selected filters.", styles["Normal"]))
    else:
        headers = list(rows[0].keys())
        data = [headers]
        for row in rows[:250]:
            data.append([str(row.get(h, ""))[:48] for h in headers])
        table = Table(data, repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ]
            )
        )
        story.append(table)
        if len(rows) > 250:
            story.append(Spacer(1, 8))
            story.append(Paragraph(f"Showing first 250 of {len(rows)} rows.", styles["Normal"]))

    doc.build(story)
    return buf.getvalue()


def export_payload(
    report_key: str,
    payload: dict[str, Any],
    fmt: str,
    *,
    user: User,
    subtitle: str,
) -> tuple[bytes | str, str, str]:
    """Return content, media_type, filename stem."""
    from app.core.reports_catalog import report_definition

    definition = report_definition(report_key) or {}
    title = definition.get("label") or report_key.replace("-", " ").title()
    sheets = payload.get("sheets")
    rows = payload.get("rows") or []

    if fmt == "csv":
        if sheets and len(sheets) > 1:
            primary = rows or next(iter(sheets.values()), [])
            content = rows_to_csv(primary)
        else:
            content = rows_to_csv(rows)
        return content, "text/csv", report_key

    if fmt == "xlsx":
        content = payload_to_xlsx(
            title=title,
            subtitle=subtitle,
            user=user,
            rows=rows,
            sheets=sheets,
        )
        media = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        return content, media, report_key

    if fmt == "pdf":
        content = payload_to_pdf(title=title, subtitle=subtitle, user=user, rows=rows)
        return content, "application/pdf", report_key

    raise ValueError(f"Unsupported format: {fmt}")
