"""initial_schema

Revision ID: 70ed65093b89
Revises: 
Create Date: 2026-05-16 15:48:35.382902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70ed65093b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Bootstrap full schema from SQLAlchemy models (empty database only)."""
    from app.core.database import Base
    import app.models  # noqa: F401 — register all tables

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
