"""Transactional email: events, templates, SMTP provider, and email_logs."""

from app.services.email.events import EmailEvent
from app.services.email.service import (
    booking_cancelled_email,
    booking_confirmed_email,
    booking_rescheduled_email,
    enqueue_email_event,
    enqueue_parent_invoice_email,
    enqueue_password_reset_email,
    enqueue_report_published_email,
    invite_portal_email,
    is_smtp_configured,
    leave_admin_summary_email,
    leave_approved_therapist_email,
    leave_pending_hr_email,
    leave_rejected_therapist_email,
    leave_sessions_cancelled_email,
    leave_sessions_reinstated_email,
    parent_invoice_ready_email,
    password_reset_email,
    schedule_email_log_delivery,
    send_email,
    send_payment_reminder_email,
    therapist_staff_invite_email,
)

__all__ = [
    "EmailEvent",
    "booking_cancelled_email",
    "booking_confirmed_email",
    "booking_rescheduled_email",
    "enqueue_email_event",
    "enqueue_parent_invoice_email",
    "enqueue_password_reset_email",
    "enqueue_report_published_email",
    "invite_portal_email",
    "is_smtp_configured",
    "leave_admin_summary_email",
    "leave_approved_therapist_email",
    "leave_pending_hr_email",
    "leave_rejected_therapist_email",
    "leave_sessions_cancelled_email",
    "leave_sessions_reinstated_email",
    "parent_invoice_ready_email",
    "password_reset_email",
    "schedule_email_log_delivery",
    "send_email",
    "send_payment_reminder_email",
    "therapist_staff_invite_email",
]
