/** Client-side finance report catalog so the picker works even when billing APIs are off. */

export const FINANCE_CATEGORY = { id: 'finance', label: 'Finance' }

export const FINANCE_REPORTS = [
  {
    key: 'therapist-payout-preview',
    label: 'Therapist payout preview',
    description: 'Projected therapist pay for the billing month. Generate before export. Close month freezes the snapshot.',
    category: 'finance',
    filters: ['month', 'date_from', 'date_to', 'product_module', 'status', 'case_id', 'therapist_user_id'],
    formats: ['csv', 'xlsx'],
    generateFirst: true,
    closeMonth: true,
    source: 'finance',
  },
  {
    key: 'monthly-billing',
    label: 'Monthly billing',
    description: 'Client invoices for the selected billing month.',
    category: 'finance',
    filters: ['month', 'date_from', 'date_to', 'product_module', 'status'],
    statusOptions: [
      { value: '', label: 'All statuses' },
      { value: 'GENERATED', label: 'Generated' },
      { value: 'ISSUED', label: 'Issued' },
      { value: 'SENT', label: 'Sent' },
      { value: 'PARTIALLY_PAID', label: 'Partially paid' },
      { value: 'PAID', label: 'Paid' },
      { value: 'OVERDUE', label: 'Overdue' },
    ],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'outstanding',
    label: 'Outstanding balances',
    description: 'Current unpaid client invoices. Month limits the cohort; amounts are today’s balances.',
    category: 'finance',
    filters: ['month', 'date_from', 'date_to', 'product_module', 'status'],
    statusOptions: [
      { value: '', label: 'All statuses' },
      { value: 'GENERATED', label: 'Generated' },
      { value: 'ISSUED', label: 'Issued' },
      { value: 'SENT', label: 'Sent' },
      { value: 'PARTIALLY_PAID', label: 'Partially paid' },
      { value: 'OVERDUE', label: 'Overdue' },
    ],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'collections',
    label: 'Collections',
    description: 'Family payments received in the IST period. Confirmed cash only in the total.',
    category: 'finance',
    filters: ['month', 'date_from', 'date_to', 'product_module', 'status'],
    statusOptions: [
      { value: '', label: 'All statuses' },
      { value: 'CONFIRMED', label: 'Confirmed' },
      { value: 'PENDING_REVIEW', label: 'Pending review' },
      { value: 'REJECTED', label: 'Rejected' },
    ],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'therapist-payouts',
    label: 'Therapist payouts',
    description: 'Therapist payout statements for the billing month (not paid-at).',
    category: 'finance',
    filters: ['month', 'status'],
    statusOptions: [
      { value: '', label: 'All statuses' },
      { value: 'DRAFT', label: 'Draft' },
      { value: 'IN_REVIEW', label: 'In review' },
      { value: 'APPROVED', label: 'Approved' },
      { value: 'PAID', label: 'Paid' },
      { value: 'QUERIED', label: 'Queried' },
      { value: 'REJECTED', label: 'Rejected' },
    ],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'pending-payout-approvals',
    label: 'Pending payout approvals',
    description: 'Therapist statements still in review.',
    category: 'finance',
    filters: ['month'],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'ledger-missing',
    label: 'Ledger missing',
    description: 'Cases with completed sessions in the month and no ledger row.',
    category: 'finance',
    filters: ['month', 'product_module'],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'manual-adjustments',
    label: 'Manual adjustments',
    description: 'Manual fees, discounts, and therapist manual lines.',
    category: 'finance',
    filters: ['month'],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'revenue-by-service',
    label: 'Invoiced by service',
    description: 'Client invoice totals grouped by service type. Not recognised revenue.',
    category: 'finance',
    filters: ['month', 'product_module'],
    formats: ['csv', 'xlsx'],
    source: 'finance',
  },
  {
    key: 'margin-by-case',
    label: 'Margin by case',
    description: 'Client billable vs therapist pay for the month.',
    category: 'finance',
    filters: ['month', 'product_module'],
    formats: ['csv', 'xlsx'],
    generateFirst: true,
    source: 'finance',
  },
]

export const PAGE_REPORTS = [
  {
    key: 'ticket-report',
    label: 'Ticket report',
    description: 'Open and in-progress tickets opened during an IST range. POSH and CPP stay as counts.',
    category: 'support',
    href: '/admin/support?tab=ticket-report',
    kind: 'page',
    source: 'page',
    filters: [],
    formats: [],
  },
  {
    key: 'therapist-attention',
    label: 'Therapist attention',
    description: 'Account, assignment, last login, last app activity, and missing logs.',
    category: 'quality',
    href: '/admin/therapist-attention',
    kind: 'page',
    source: 'page',
    filters: [],
    formats: [],
  },
  {
    key: 'data-exceptions',
    label: 'Data exceptions',
    description: 'Live Layer-1 checks as of generation. Nothing is auto-repaired.',
    category: 'quality',
    href: '/admin/data-exceptions',
    kind: 'page',
    source: 'page',
    filters: [],
    formats: [],
  },
  {
    key: 'clinical-review',
    label: 'Clinical review queue',
    description: 'Approve and publish monthly and observation documents. Separate from exports.',
    category: 'clinical',
    href: '/admin/reports',
    kind: 'page',
    source: 'page',
    filters: [],
    formats: [],
  },
]
